name: single_value_cubit
description: Simple single value cubit. Works as a simple state manager for inputs, scrolls, flags etc. Works best as injected and observed by other blocs/cubits.
version: 1.1.0
homepage: https://github.com/thecodebrothers/single-value-cubit
repository: https://github.com/thecodebrothers/single-value-cubit

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: 3.0.0
